### ISSUE TITLE
Community reachout 

### ISSUE THREAD

**Issue by jonniebigodes** [sheriffMoose/storybook-ngx#2]
Hi @sheriffMoose!

I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm reaching out to you by opening this issue, as during my weekly rounds of community content (i.e., addons, articles, videos) I came across your addon and have been testing it, and it's amazing. I've shared it with the team, and they were thrilled to learn about it as well. With that in mind, I would like to follow up with you on this if you're ok with it. Could you message me (same username) in our [Discord Server](https://discord.gg/storybook)?

Looking forward to hearing from you.

Hope you have a fantastic day.

Stay safe

**Comment by sheriffMoose** [comment]
Hi @jonniebigodes, I reached out to you over discord and I am awaiting your response. Thank you very much for reaching out.
